services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "12000:80"
    volumes:
      - ./database:/var/www/html/database
      - ./storage:/var/www/html/storage
      - ./.env:/var/www/html/.env  # <--- persist .env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
